#!/bin/bash
# Test script for Pause Freeze functionality

echo "==================================="
echo "Pause Freeze 功能测试指南"
echo "==================================="
echo ""
echo "本脚本提供测试 Pause 真正静止功能的指导"
echo ""
echo "📋 测试步骤："
echo ""
echo "1. 启动 SimRobot："
echo "   ./Build/Linux/SimRobot/Develop/SimRobot"
echo ""
echo "2. 加载场景："
echo "   File -> Open -> Config/Scenes/[选择一个场景]"
echo ""
echo "3. 启动 GameController："
echo "   在另一个终端运行 GameController"
echo ""
echo "4. 测试场景 A - 站立时暂停："
echo "   a) 让机器人进入 Playing 状态"
echo "   b) 观察机器人站立姿态"
echo "   c) 点击 GameController 的 '⏸️ 暂停 / PAUSE' 按钮"
echo "   d) ✅ 期望：机器人完全静止，无踏步、无摆动"
echo "   e) 点击 '▶️ 恢复 / RESUME' 按钮"
echo "   f) ✅ 期望：机器人恢复正常站立"
echo ""
echo "5. 测试场景 B - 行走时暂停："
echo "   a) 让机器人开始行走"
echo "   b) 在行走过程中点击 PAUSE"
echo "   c) ✅ 期望：机器人立即停止并保持当前姿态"
echo "   d) 观察 10-30 秒"
echo "   e) ✅ 期望：持续保持静止，无任何运动"
echo "   f) 点击 RESUME"
echo "   g) ✅ 期望：机器人可以继续行走或站立"
echo ""
echo "6. 测试场景 C - 长时间暂停："
echo "   a) 机器人站立或行走时点击 PAUSE"
echo "   b) 等待 1-2 分钟"
echo "   c) ✅ 期望：整个过程中机器人保持完全静止"
echo "   d) 点击 RESUME"
echo "   e) ✅ 期望：机器人正常恢复"
echo ""
echo "🔍 观察要点："
echo ""
echo "  ❌ 不应该出现："
echo "     - 原地踏步 (walking-in-place)"
echo "     - 重心左右摆动"
echo "     - 脚部抬起/放下动作"
echo "     - 关节周期性调整"
echo ""
echo "  ✅ 应该看到："
echo "     - 机器人姿态完全固定"
echo "     - 关节角度不变"
echo "     - 视觉上完全静止（除了必要的最小平衡输出）"
echo ""
echo "📊 调试信息："
echo ""
echo "  在 SimRobot 中可以查看："
echo "  - representation:MotionInfo -> executedPhase"
echo "    暂停时应该显示 'freeze'"
echo "  - representation:GameState -> paused"
echo "    暂停时应该为 'true'"
echo "  - representation:JointRequest"
echo "    暂停时关节角度应该保持不变"
echo ""
echo "🐛 如果出现问题："
echo ""
echo "  1. 检查编译是否成功："
echo "     cd Make/Linux && ./generate && cmake --build ../../Build/Linux/CMake/Develop --target SimRobot"
echo ""
echo "  2. 检查 GameState.paused 是否正确设置："
echo "     在 SimRobot 中查看 representation:GameState"
echo ""
echo "  3. 检查 MotionInfo.executedPhase："
echo "     暂停时应该是 'freeze' 而不是 'walk' 或 'stand'"
echo ""
echo "  4. 查看日志输出："
echo "     检查是否有相关错误信息"
echo ""
echo "==================================="
echo "测试完成后，请记录结果并报告任何问题"
echo "==================================="
